#!/sbin/sh
# @overview Patch utility script
# @since 2018.03.05, 00:00
# @version 2018.11.06, 04:39

SCRIPT_PATH=`dirname "$0"`
SCRIPT_PATH=`realpath "$SCRIPT_PATH"`

# Saving source path
ORIGPATH=`pwd`

# Scan all `patch-config`s...
DIRS=`find_ . -name "patch-config*" \
  | sed 's/[\\]/\//g;s/\/[^\/]*$//g'`

# Process all found folders...
for D in $DIRS; do
  echo ""
  echo "Processing $D..."
  cd "$D"
  sh "$SCRIPT_PATH/patch-tool-apply"
  cd "$ORIGPATH"
done
